version: '1.0'
services:
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: lazystudent
    # volumes:
    #   - mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    
  backend:
    build: .
    image: jamesmlewi/lazy-backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db

  # mysql:
  #   image: "mysql:5.7.41"

